### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by kc9ryt** [mimolabs/docker-compose#1]
Hello, I am trying to install mimo but the installer keeps failing. I tried running the ./docker-logs.sh but the file doesn't exist.
<img width="1200" alt="screen shot 2018-06-25 at 11 32 00 pm" src="https://user-images.githubusercontent.com/3506952/41887845-83194d74-78d0-11e8-8394-f4c240b13764.png">

**Comment by simonmorley** [comment]
Can you post installation issues here:

https://discuss.oh-mimo.com/
